# Generated by Django 4.2.6 on 2023-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='author adi')),
            ],
            options={
                'verbose_name': 'author adi',
                'verbose_name_plural': 'author adlari',
                'ordering': ('name',),
            },
        ),
    ]
