# Generated by Django 4.2.6 on 2023-10-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='tag adi')),
            ],
            options={
                'verbose_name': 'tag adi',
                'verbose_name_plural': 'tag adlari',
                'ordering': ('name',),
            },
        ),
    ]
