# Generated by Django 4.2.6 on 2023-10-23 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='adi')),
                ('seria_number', models.CharField(max_length=255, verbose_name='seria nomresi')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.category')),
                ('tags', models.ManyToManyField(to='my_app.keywords')),
            ],
            options={
                'verbose_name': 'kitab',
                'verbose_name_plural': 'kitablar',
                'ordering': ('name',),
            },
        ),
    ]
